#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Virtual_Guitar_Teacher.Resource", IsApplication=true)]

namespace Virtual_Guitar_Teacher
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ball_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ball_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ball_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ball_purple = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ball_red = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_musical = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_play_01 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_record_01 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_tune_01 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BorderedSquare = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon_512x512 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int loading_screen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Neck_Acustic_01 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int parquet_texture_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int parquet_texture_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int play = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int recorder_cell_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int recorder_cell_bg_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int tune = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tutorial = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int vinyl = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int btnPlayer = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int btnRecorder = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btnTuner = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int btnTutor = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int closestNote = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int frequencyIndicator = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int fret1 = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int fret2 = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int fret3 = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int fret4 = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int fret5 = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int fret6 = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int gridLayout = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int guitarBG = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int openString = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int tableLayout = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow2 = 2131099660;
			
			// aapt resource value: 0x7f060014
			public const int tableRow3 = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int tuneBar = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int view0 = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int view7 = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Player = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Recorder = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Tuner = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tutor = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SharePicture = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SongsFolderPath = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int Theme_Dark = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Light = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Theme_Musical = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Theme_Play = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Theme_Record = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Theme_Tune = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
