#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Virtual_Guitar_Teacher.Resource", IsApplication=true)]

namespace Virtual_Guitar_Teacher
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SharpShowcaseView.Resource.Attribute.showcaseViewStyle = global::Virtual_Guitar_Teacher.Resource.Attribute.showcaseViewStyle;
			global::SharpShowcaseView.Resource.Attribute.sv_backgroundColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_backgroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonBackgroundColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_buttonBackgroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonForegroundColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_buttonForegroundColor;
			global::SharpShowcaseView.Resource.Attribute.sv_buttonText = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_buttonText;
			global::SharpShowcaseView.Resource.Attribute.sv_detailTextAppearance = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_detailTextAppearance;
			global::SharpShowcaseView.Resource.Attribute.sv_detailTextColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_detailTextColor;
			global::SharpShowcaseView.Resource.Attribute.sv_showcaseColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_showcaseColor;
			global::SharpShowcaseView.Resource.Attribute.sv_titleTextAppearance = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_titleTextAppearance;
			global::SharpShowcaseView.Resource.Attribute.sv_titleTextColor = global::Virtual_Guitar_Teacher.Resource.Attribute.sv_titleTextColor;
			global::SharpShowcaseView.Resource.Drawable.btn_cling_normal = global::Virtual_Guitar_Teacher.Resource.Drawable.btn_cling_normal;
			global::SharpShowcaseView.Resource.Drawable.btn_cling_pressed = global::Virtual_Guitar_Teacher.Resource.Drawable.btn_cling_pressed;
			global::SharpShowcaseView.Resource.Drawable.cling = global::Virtual_Guitar_Teacher.Resource.Drawable.cling;
			global::SharpShowcaseView.Resource.Drawable.cling_bleached = global::Virtual_Guitar_Teacher.Resource.Drawable.cling_bleached;
			global::SharpShowcaseView.Resource.Drawable.cling_button_bg = global::Virtual_Guitar_Teacher.Resource.Drawable.cling_button_bg;
			global::SharpShowcaseView.Resource.Drawable.hand = global::Virtual_Guitar_Teacher.Resource.Drawable.hand;
			global::SharpShowcaseView.Resource.Id.showcase_button = global::Virtual_Guitar_Teacher.Resource.Id.showcase_button;
			global::SharpShowcaseView.Resource.Id.showcase_sub_text = global::Virtual_Guitar_Teacher.Resource.Id.showcase_sub_text;
			global::SharpShowcaseView.Resource.Id.showcase_title_text = global::Virtual_Guitar_Teacher.Resource.Id.showcase_title_text;
			global::SharpShowcaseView.Resource.Layout.handy = global::Virtual_Guitar_Teacher.Resource.Layout.handy;
			global::SharpShowcaseView.Resource.Layout.showcase_button = global::Virtual_Guitar_Teacher.Resource.Layout.showcase_button;
			global::SharpShowcaseView.Resource.String.ok = global::Virtual_Guitar_Teacher.Resource.String.ok;
			global::SharpShowcaseView.Resource.Style.ShowcaseButton = global::Virtual_Guitar_Teacher.Resource.Style.ShowcaseButton;
			global::SharpShowcaseView.Resource.Style.ShowcaseView = global::Virtual_Guitar_Teacher.Resource.Style.ShowcaseView;
			global::SharpShowcaseView.Resource.Style.ShowcaseView_Light = global::Virtual_Guitar_Teacher.Resource.Style.ShowcaseView_Light;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Detail = global::Virtual_Guitar_Teacher.Resource.Style.TextAppearance_ShowcaseView_Detail;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Detail_Light = global::Virtual_Guitar_Teacher.Resource.Style.TextAppearance_ShowcaseView_Detail_Light;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Title = global::Virtual_Guitar_Teacher.Resource.Style.TextAppearance_ShowcaseView_Title;
			global::SharpShowcaseView.Resource.Style.TextAppearance_ShowcaseView_Title_Light = global::Virtual_Guitar_Teacher.Resource.Style.TextAppearance_ShowcaseView_Title_Light;
			global::SharpShowcaseView.Resource.Styleable.CustomTheme = global::Virtual_Guitar_Teacher.Resource.Styleable.CustomTheme;
			global::SharpShowcaseView.Resource.Styleable.CustomTheme_showcaseViewStyle = global::Virtual_Guitar_Teacher.Resource.Styleable.CustomTheme_showcaseViewStyle;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_backgroundColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_backgroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonBackgroundColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_buttonBackgroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonForegroundColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_buttonForegroundColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_buttonText = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_buttonText;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_detailTextAppearance = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_detailTextAppearance;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_detailTextColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_detailTextColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_showcaseColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_showcaseColor;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_titleTextAppearance = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_titleTextAppearance;
			global::SharpShowcaseView.Resource.Styleable.ShowcaseView_sv_titleTextColor = global::Virtual_Guitar_Teacher.Resource.Styleable.ShowcaseView_sv_titleTextColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int showcaseViewStyle = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int sv_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int sv_buttonBackgroundColor = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int sv_buttonForegroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int sv_buttonText = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int sv_detailTextAppearance = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int sv_detailTextColor = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int sv_showcaseColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int sv_titleTextAppearance = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int sv_titleTextColor = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ball_aqua = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ball_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ball_green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ball_orange = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ball_purple = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ball_red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ball_yellow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_musical = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_play_01 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_record_01 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_record_02 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_tune_01 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_cling_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_cling_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cling = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cling_bleached = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cling_button_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int hand = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon_512x512 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int loading_screen = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Neck_Acustic_01 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int parquet_texture_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int parquet_texture_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int play = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int record = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int recorder_cell_bg = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int recorder_cell_bg_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int smiley_happy = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int smiley_sad = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int stop = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tune = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tuner_dial = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tuner_gauge = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tutorial = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int vinyl = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040007
			public const int btnNext = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int btnPlayer = 2130968580;
			
			// aapt resource value: 0x7f040024
			public const int btnRecord = 2130968612;
			
			// aapt resource value: 0x7f040006
			public const int btnRecorder = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int btnTuner = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int btnTutor = 2130968579;
			
			// aapt resource value: 0x7f040025
			public const int closestNote = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int content = 2130968614;
			
			// aapt resource value: 0x7f04002c
			public const int frequencyGauge = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int frequencyIndicator = 2130968619;
			
			// aapt resource value: 0x7f040013
			public const int fret1 = 2130968595;
			
			// aapt resource value: 0x7f04006e
			public const int fret1_string_A = 2130968686;
			
			// aapt resource value: 0x7f040074
			public const int fret1_string_B = 2130968692;
			
			// aapt resource value: 0x7f040070
			public const int fret1_string_D = 2130968688;
			
			// aapt resource value: 0x7f04006c
			public const int fret1_string_E = 2130968684;
			
			// aapt resource value: 0x7f040072
			public const int fret1_string_G = 2130968690;
			
			// aapt resource value: 0x7f040076
			public const int fret1_string_e = 2130968694;
			
			// aapt resource value: 0x7f040012
			public const int fret2 = 2130968594;
			
			// aapt resource value: 0x7f040062
			public const int fret2_string_A = 2130968674;
			
			// aapt resource value: 0x7f040068
			public const int fret2_string_B = 2130968680;
			
			// aapt resource value: 0x7f040064
			public const int fret2_string_D = 2130968676;
			
			// aapt resource value: 0x7f040060
			public const int fret2_string_E = 2130968672;
			
			// aapt resource value: 0x7f040066
			public const int fret2_string_G = 2130968678;
			
			// aapt resource value: 0x7f04006a
			public const int fret2_string_e = 2130968682;
			
			// aapt resource value: 0x7f040011
			public const int fret3 = 2130968593;
			
			// aapt resource value: 0x7f040056
			public const int fret3_string_A = 2130968662;
			
			// aapt resource value: 0x7f04005c
			public const int fret3_string_B = 2130968668;
			
			// aapt resource value: 0x7f040058
			public const int fret3_string_D = 2130968664;
			
			// aapt resource value: 0x7f040054
			public const int fret3_string_E = 2130968660;
			
			// aapt resource value: 0x7f04005a
			public const int fret3_string_G = 2130968666;
			
			// aapt resource value: 0x7f04005e
			public const int fret3_string_e = 2130968670;
			
			// aapt resource value: 0x7f040010
			public const int fret4 = 2130968592;
			
			// aapt resource value: 0x7f04004a
			public const int fret4_string_A = 2130968650;
			
			// aapt resource value: 0x7f040050
			public const int fret4_string_B = 2130968656;
			
			// aapt resource value: 0x7f04004c
			public const int fret4_string_D = 2130968652;
			
			// aapt resource value: 0x7f040048
			public const int fret4_string_E = 2130968648;
			
			// aapt resource value: 0x7f04004e
			public const int fret4_string_G = 2130968654;
			
			// aapt resource value: 0x7f040052
			public const int fret4_string_e = 2130968658;
			
			// aapt resource value: 0x7f04000f
			public const int fret5 = 2130968591;
			
			// aapt resource value: 0x7f04003e
			public const int fret5_string_A = 2130968638;
			
			// aapt resource value: 0x7f040044
			public const int fret5_string_B = 2130968644;
			
			// aapt resource value: 0x7f040040
			public const int fret5_string_D = 2130968640;
			
			// aapt resource value: 0x7f04003c
			public const int fret5_string_E = 2130968636;
			
			// aapt resource value: 0x7f040042
			public const int fret5_string_G = 2130968642;
			
			// aapt resource value: 0x7f040046
			public const int fret5_string_e = 2130968646;
			
			// aapt resource value: 0x7f04000e
			public const int fret6 = 2130968590;
			
			// aapt resource value: 0x7f040032
			public const int fret6_string_A = 2130968626;
			
			// aapt resource value: 0x7f040038
			public const int fret6_string_B = 2130968632;
			
			// aapt resource value: 0x7f040034
			public const int fret6_string_D = 2130968628;
			
			// aapt resource value: 0x7f040030
			public const int fret6_string_E = 2130968624;
			
			// aapt resource value: 0x7f040036
			public const int fret6_string_G = 2130968630;
			
			// aapt resource value: 0x7f04003a
			public const int fret6_string_e = 2130968634;
			
			// aapt resource value: 0x7f04002a
			public const int gridLayout = 2130968618;
			
			// aapt resource value: 0x7f040009
			public const int guitarBG = 2130968585;
			
			// aapt resource value: 0x7f040027
			public const int handle = 2130968615;
			
			// aapt resource value: 0x7f040029
			public const int lstRecordings = 2130968617;
			
			// aapt resource value: 0x7f040014
			public const int openString = 2130968596;
			
			// aapt resource value: 0x7f04007a
			public const int openString_string_A = 2130968698;
			
			// aapt resource value: 0x7f040080
			public const int openString_string_B = 2130968704;
			
			// aapt resource value: 0x7f04007c
			public const int openString_string_D = 2130968700;
			
			// aapt resource value: 0x7f040078
			public const int openString_string_E = 2130968696;
			
			// aapt resource value: 0x7f04007e
			public const int openString_string_G = 2130968702;
			
			// aapt resource value: 0x7f040082
			public const int openString_string_e = 2130968706;
			
			// aapt resource value: 0x7f040000
			public const int showcase_button = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int showcase_sub_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int showcase_title_text = 2130968577;
			
			// aapt resource value: 0x7f040028
			public const int slidingDrawer = 2130968616;
			
			// aapt resource value: 0x7f040015
			public const int stingsColors = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int string_A = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int string_B = 2130968607;
			
			// aapt resource value: 0x7f04001b
			public const int string_D = 2130968603;
			
			// aapt resource value: 0x7f040017
			public const int string_E = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int string_G = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int string_e = 2130968609;
			
			// aapt resource value: 0x7f04000a
			public const int tableLayout = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int tableRow1 = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int tableRow2 = 2130968589;
			
			// aapt resource value: 0x7f040022
			public const int tableRow3 = 2130968610;
			
			// aapt resource value: 0x7f04006d
			public const int tableRow_fret1_string_A = 2130968685;
			
			// aapt resource value: 0x7f040073
			public const int tableRow_fret1_string_B = 2130968691;
			
			// aapt resource value: 0x7f04006f
			public const int tableRow_fret1_string_D = 2130968687;
			
			// aapt resource value: 0x7f04006b
			public const int tableRow_fret1_string_E = 2130968683;
			
			// aapt resource value: 0x7f040071
			public const int tableRow_fret1_string_G = 2130968689;
			
			// aapt resource value: 0x7f040075
			public const int tableRow_fret1_string_e = 2130968693;
			
			// aapt resource value: 0x7f040061
			public const int tableRow_fret2_string_A = 2130968673;
			
			// aapt resource value: 0x7f040067
			public const int tableRow_fret2_string_B = 2130968679;
			
			// aapt resource value: 0x7f040063
			public const int tableRow_fret2_string_D = 2130968675;
			
			// aapt resource value: 0x7f04005f
			public const int tableRow_fret2_string_E = 2130968671;
			
			// aapt resource value: 0x7f040065
			public const int tableRow_fret2_string_G = 2130968677;
			
			// aapt resource value: 0x7f040069
			public const int tableRow_fret2_string_e = 2130968681;
			
			// aapt resource value: 0x7f040055
			public const int tableRow_fret3_string_A = 2130968661;
			
			// aapt resource value: 0x7f04005b
			public const int tableRow_fret3_string_B = 2130968667;
			
			// aapt resource value: 0x7f040057
			public const int tableRow_fret3_string_D = 2130968663;
			
			// aapt resource value: 0x7f040053
			public const int tableRow_fret3_string_E = 2130968659;
			
			// aapt resource value: 0x7f040059
			public const int tableRow_fret3_string_G = 2130968665;
			
			// aapt resource value: 0x7f04005d
			public const int tableRow_fret3_string_e = 2130968669;
			
			// aapt resource value: 0x7f040049
			public const int tableRow_fret4_string_A = 2130968649;
			
			// aapt resource value: 0x7f04004f
			public const int tableRow_fret4_string_B = 2130968655;
			
			// aapt resource value: 0x7f04004b
			public const int tableRow_fret4_string_D = 2130968651;
			
			// aapt resource value: 0x7f040047
			public const int tableRow_fret4_string_E = 2130968647;
			
			// aapt resource value: 0x7f04004d
			public const int tableRow_fret4_string_G = 2130968653;
			
			// aapt resource value: 0x7f040051
			public const int tableRow_fret4_string_e = 2130968657;
			
			// aapt resource value: 0x7f04003d
			public const int tableRow_fret5_string_A = 2130968637;
			
			// aapt resource value: 0x7f040043
			public const int tableRow_fret5_string_B = 2130968643;
			
			// aapt resource value: 0x7f04003f
			public const int tableRow_fret5_string_D = 2130968639;
			
			// aapt resource value: 0x7f04003b
			public const int tableRow_fret5_string_E = 2130968635;
			
			// aapt resource value: 0x7f040041
			public const int tableRow_fret5_string_G = 2130968641;
			
			// aapt resource value: 0x7f040045
			public const int tableRow_fret5_string_e = 2130968645;
			
			// aapt resource value: 0x7f040031
			public const int tableRow_fret6_string_A = 2130968625;
			
			// aapt resource value: 0x7f040037
			public const int tableRow_fret6_string_B = 2130968631;
			
			// aapt resource value: 0x7f040033
			public const int tableRow_fret6_string_D = 2130968627;
			
			// aapt resource value: 0x7f04002f
			public const int tableRow_fret6_string_E = 2130968623;
			
			// aapt resource value: 0x7f040035
			public const int tableRow_fret6_string_G = 2130968629;
			
			// aapt resource value: 0x7f040039
			public const int tableRow_fret6_string_e = 2130968633;
			
			// aapt resource value: 0x7f040079
			public const int tableRow_openString_string_A = 2130968697;
			
			// aapt resource value: 0x7f04007f
			public const int tableRow_openString_string_B = 2130968703;
			
			// aapt resource value: 0x7f04007b
			public const int tableRow_openString_string_D = 2130968699;
			
			// aapt resource value: 0x7f040077
			public const int tableRow_openString_string_E = 2130968695;
			
			// aapt resource value: 0x7f04007d
			public const int tableRow_openString_string_G = 2130968701;
			
			// aapt resource value: 0x7f040081
			public const int tableRow_openString_string_e = 2130968705;
			
			// aapt resource value: 0x7f040018
			public const int tableRow_string_A = 2130968600;
			
			// aapt resource value: 0x7f04001e
			public const int tableRow_string_B = 2130968606;
			
			// aapt resource value: 0x7f04001a
			public const int tableRow_string_D = 2130968602;
			
			// aapt resource value: 0x7f040016
			public const int tableRow_string_E = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int tableRow_string_G = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int tableRow_string_e = 2130968608;
			
			// aapt resource value: 0x7f040008
			public const int textView1 = 2130968584;
			
			// aapt resource value: 0x7f04002e
			public const int txtFrequency = 2130968622;
			
			// aapt resource value: 0x7f04000c
			public const int view0 = 2130968588;
			
			// aapt resource value: 0x7f040023
			public const int view7 = 2130968611;
			
			// aapt resource value: 0x7f04002d
			public const int volumeBar = 2130968621;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int handy = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainHelp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Player = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Recorder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int showcase_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Tuner = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Tutor = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int AudioRecordPermissionAlertMsg = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int AudioRecordPermissionAlertTitle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ok = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ShowcaseButton = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int ShowcaseView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ShowcaseView_Light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_ShowcaseView_Detail = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_ShowcaseView_Detail_Light = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_ShowcaseView_Title = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_ShowcaseView_Title_Light = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int Theme_Dark = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int Theme_Light = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int Theme_Musical = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int Theme_Play = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int Theme_Record = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int Theme_Splash = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int Theme_Tune = 2131099659;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomTheme = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public const int CustomTheme_showcaseViewStyle = 0;
			
			public static int[] ShowcaseView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int ShowcaseView_sv_backgroundColor = 0;
			
			// aapt resource value: 3
			public const int ShowcaseView_sv_buttonBackgroundColor = 3;
			
			// aapt resource value: 4
			public const int ShowcaseView_sv_buttonForegroundColor = 4;
			
			// aapt resource value: 5
			public const int ShowcaseView_sv_buttonText = 5;
			
			// aapt resource value: 6
			public const int ShowcaseView_sv_detailTextAppearance = 6;
			
			// aapt resource value: 1
			public const int ShowcaseView_sv_detailTextColor = 1;
			
			// aapt resource value: 8
			public const int ShowcaseView_sv_showcaseColor = 8;
			
			// aapt resource value: 7
			public const int ShowcaseView_sv_titleTextAppearance = 7;
			
			// aapt resource value: 2
			public const int ShowcaseView_sv_titleTextColor = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
